---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: certbot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: certbot
        role: master
        tier: app
    spec:
      containers:
      - name: certbot
        image: adilsoncarvalho/certbot
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
        - mountPath: /etc/letsencrypt
          name: certbot-certificates
      volumes:
      - name: certbot-certificates
        gcePersistentDisk:
          pdName: certbot-certificates
          fsType: ext4
